<?php
/**
 * PDF Generation for Inventory Report
 * Generates actual PDF files without requiring external applications
 */

require_once 'auth.php';
requireLogin();

require_once 'dbconnection.php';

// Set timezone to Philippine Time
date_default_timezone_set('Asia/Manila');

// Get search parameter if any
$search = $_GET['search'] ?? '';
$search_param = '';

// Build query
if (!empty($search)) {
    $search_param = "%" . $search . "%";
    $conn = getDBConnection();
    $stmt = $conn->prepare("SELECT * FROM items WHERE item_name LIKE ? OR isles LIKE ? OR shelf_position LIKE ? ORDER BY item_id DESC");
    $stmt->bind_param("sss", $search_param, $search_param, $search_param);
    $stmt->execute();
    $result = $stmt->get_result();
    $items = [];
    while ($row = $result->fetch_assoc()) {
        $items[] = $row;
    }
    $stmt->close();
} else {
    $conn = getDBConnection();
    $sql = "SELECT * FROM items ORDER BY item_id DESC";
    $result = $conn->query($sql);
    $items = [];
    while ($row = $result->fetch_assoc()) {
        $items[] = $row;
    }
}

closeDBConnection($conn);

$user = getCurrentUser();

// Generate PDF using HTML to PDF approach (browser will handle conversion)
// This creates a print-optimized HTML page that can be saved as PDF
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Inventory Report - <?php echo date('Y-m-d'); ?></title>
    <style>
        @media print {
            @page { 
                margin: 15mm;
                size: A4;
            }
            body { margin: 0; }
            .no-print { display: none; }
        }
        body { 
            font-family: Arial, sans-serif; 
            font-size: 10pt; 
            margin: 20px;
            color: #333;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px;
            border-bottom: 3px solidrgb(24, 129, 227);
            padding-bottom: 15px;
        }
        h1 { 
            color:rgb(24, 197, 227); 
            margin: 0;
            font-size: 24pt;
            font-weight: bold;
        }
        h2 { 
            color:rgb(0, 22, 82); 
            border-bottom: 2px solidrgb(0, 36, 82); 
            padding-bottom: 5px;
            margin-top: 20px;
            font-size: 14pt;
        }
        .info {
            margin: 10px 0;
            font-size: 9pt;
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px;
            font-size: 9pt;
        }
        th { 
            background-color:rgb(24, 146, 227); 
            color: white; 
            padding: 8px 5px; 
            text-align: left;
            font-weight: bold;
        }
        td { 
            padding: 6px 5px; 
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) { 
            background-color: #f9f9f9; 
        }
        .total-row { 
            font-weight: bold; 
            background-color: #f0f0f0;
            border-top: 2px solid #333;
        }
        .footer { 
            margin-top: 30px; 
            text-align: center; 
            font-size: 8pt; 
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .print-btn {
            background: linear-gradient(135deg,rgb(24, 105, 227) 0%,rgb(20, 95, 192) 100%);
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 20px;
        }
        .print-btn:hover {
            background: linear-gradient(135deg,rgb(20, 143, 192) 0%,rgb(16, 83, 160) 100%);
        }
    </style>
    <script>
        function printPDF() {
            window.print();
        }
        
        // Auto-print on load (optional - comment out if you don't want auto-print)
        // window.onload = function() { setTimeout(printPDF, 500); }
    </script>
</head>
<body>
    <div class="no-print" style="text-align: center; margin-bottom: 20px;">
        <button onclick="printPDF()" class="print-btn">Print / Save as PDF</button>
        <p style="font-size: 12px; color: #666;">Click the button above, then use your browser's print dialog to save as PDF</p>
    </div>
    
    <div class="header">
        <h1>INCONVENIENCE STORE</h1>
        <h2>INVENTORY REPORT</h2>
        <div class="info">
            <strong>Generated:</strong> <?php echo date('F j, Y g:i A') . ''; ?><br>
            <strong>Generated by:</strong> <?php echo htmlspecialchars($user['full_name']); ?> (<?php echo htmlspecialchars($user['role']); ?>)<br>
            <?php if (!empty($search)): ?>
                <strong>Search Filter:</strong> "<?php echo htmlspecialchars($search); ?>"
            <?php endif; ?>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">ID</th>
                <th style="width: 25%;">Product Name</th>
                <th style="width: 10%;">Price</th>
                <th style="width: 10%;">Quantity</th>
                <th style="width: 15%;">Aisle</th>
                <th style="width: 15%;">Shelf Position</th>
                <th style="width: 20%;">Total Value</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $total_value = 0;
            $total_items = 0;
            $total_products = count($items);
            
            if (count($items) > 0):
                foreach ($items as $item): 
                    $item_value = $item['price'] * $item['quantity'];
                    $total_value += $item_value;
                    $total_items += $item['quantity'];
            ?>
            <tr>
                <td><?php echo htmlspecialchars($item['item_id']); ?></td>
                <td><?php echo htmlspecialchars($item['item_name']); ?></td>
                <td>&#8369;<?php echo number_format($item['price'], 2); ?></td>
                <td><?php echo htmlspecialchars($item['quantity']); ?></td>
                <td><?php echo htmlspecialchars($item['isles']); ?></td>
                <td><?php echo htmlspecialchars($item['shelf_position']); ?></td>
                <td>&#8369;<?php echo number_format($item_value, 2); ?></td>
            </tr>
            <?php 
                endforeach;
            else:
            ?>
            <tr>
                <td colspan="7" style="text-align: center; padding: 20px;">No products found in inventory.</td>
            </tr>
            <?php endif; ?>
            
            <tr class="total-row">
                <td colspan="2"><strong>SUMMARY TOTALS</strong></td>
                <td></td>
                <td><strong><?php echo number_format($total_items); ?></strong></td>
                <td colspan="2"></td>
                <td><strong>&#8369;<?php echo number_format($total_value, 2); ?></strong></td>
            </tr>
        </tbody>
    </table>
    
    <div class="footer">
        <p><strong>Report Summary</strong></p>
        <p>Total Products: <?php echo $total_products; ?> | Total Quantity: <?php echo number_format($total_items); ?> | Total Inventory Value: &#8369;<?php echo number_format($total_value, 2); ?></p>
        <p style="margin-top: 10px;">This is an automated inventory report generated by the Store Management System.</p>
        <p>Page generated on <?php echo date('F j, Y \a\t g:i A') . ''; ?></p>
    </div>
</body>
</html>
